name: Journals

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        default: false
      environment:
        type: choice
        options: [development, production]
        default: 'development'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List directory structure (Debug)
      run: ls -R

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install pdf-renamer==1.1

    - name: Run Python scripts
      run: |
        set -e
        for file in code/*.py; do
          echo "Running $file"
          timeout 300 python "$file" || { echo "Error in $file"; exit 1; }
        done
      shell: bash

    - name: Generate timestamp
      id: timestamp
      run: echo "timestamp=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_OUTPUT

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git diff --quiet && git diff --staged --quiet || (
          git commit -m "Auto update: ${{ steps.timestamp.outputs.timestamp }}

          Environment: ${{ github.event.inputs.environment }}
          Triggered by: ${{ github.event_name }}"
          # Usar GITHUB_TOKEN en la URL para autenticación
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
        )
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Status check
      if: always()
      run: |
        if [[ "${{ job.status }}" == "success" ]]; then
          echo "✅ Workflow completed successfully"
        else
          echo "❌ Workflow failed"
          exit 1
        fi